# Generated by Django 4.2.4 on 2023-08-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('essencial', models.BooleanField(default=False)),
                ('valor_planejamento', models.FloatField(default=0, verbose_name='valor do planejamento')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('CX', 'CAIXA'), ('IN', 'INTER'), ('NU', 'NUBANK')], max_length=3)),
                ('tipo', models.CharField(choices=[('pj', 'Pessoa Jurídica'), ('pf', 'Pessoa Física')], max_length=3)),
                ('valor', models.FloatField()),
                ('icone', models.ImageField(upload_to='Icone')),
            ],
        ),
    ]
